// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvihamxakxbdnaihfpuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2aWhhbXhha3hiZG5haWhmcHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMzEwNTksImV4cCI6MjA1OTkwNzA1OX0.6prETtTsVw0Y8M3dKEu4MgRLNJYPMY79YVtpjx3BxN8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);